controllers:
    resource: ../src/Controller/
    type: attribute

app_blogsite_home:
    path: /
    controller: App\Controller\HomeController::index

app_blogsite_about:
    path: /about
    controller: App\Controller\HomeController::about